name: Thanos Snap
description: 'Achieve the perfect balance for your projects'
author: 'Stanley Nguyen'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  github-token:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
